version: '3.7'

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    image: asia.gcr.io/tw/teamwork-back:0.0
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    # ports:
    # env_file:
    #   - ./.env.prod

  # 컴퓨터이름
  # my-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'myproject'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
